# Usando imagem oficial Node.js
FROM node:22-alpine

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia todo o código fonte
COPY . .

# Compila o TypeScript
RUN npm run build

# Expõe a porta que o NestJS vai rodar (geralmente 3000)
EXPOSE 3000

# Comando para rodar a aplicação compilada
CMD ["node", "dist/main"]