services:
  pgsql:
    image: postgres:11-alpine
    ports:
      - "5433:5432"
    container_name: "pgsql"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      pgsql:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "Admin123"
    ports:
      - "8085:80"
    restart: always
    depends_on:
      pgsql:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  app:
    container_name: "uniform-backend"
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run start:dev"
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        # Sync changes in the Next.js app directory for live reloading
        - action: sync
          path: ./app # Path to watch for changes (local directory)
          target: /app # Target path in the container where changes are synced
          ignore:
            - node_modules/ # Exclude node_modules/ from syncing to avoid performance issues

        # Rebuild the service when package.json changes (e.g., after adding new dependencies)
        - action: rebuild
          path: package.json # Path to watch for triggering rebuilds
    depends_on:
      pgsql:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_SYNC: ${DB_SYNC}
